name: Continuous Deployment

on: [push, pull_request]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Test
        run: |
          ./run-test.sh
        env:
          SAXON_HOME: ${{ github.workspace }}/validator/saxon
